// ==== Login Related dataDashboards ===== //
export const ON_GET_MADORS_HANDLER = 'ON_GET_MADORS_HANDLER';
export const ON_DELETE_MADORS_HANDLER = 'ON_DELETE_MADORS_HANDLER';
export const SHOW_MODAL_HANDLER = 'SHOW_MODAL_HANDLER';
export const HANDLE_OK_HANDLER = 'HANDLE_OK_HANDLER';
export const HANDLE_CHANGE_HANDLER = 'HANDLE_CHANGE_HANDLER';
export const HANDLE_CANCEL_HANDLER = 'HANDLE_CANCEL_HANDLER';
export const ON_CHANGE_HANDLER = 'ON_CHANGE_HANDLER';


