// ==== Login Related dataDashboards ===== //
export const OPEN_SESSION_HANDLER = 'OPEN_SESSION_HANDLER';
export const OPEN_MODEL_HANDLER = 'OPEN_MODEL_HANDLER';
export const CLOSE_MODEL_HANDLER = 'CLOSE_MODEL_HANDLER';
export const ON_DELETE_ROW_HANDLER = 'DELETE_ROW_HANDLER';
export const ON_ROW_SELECTED_HANDLER = 'ON_ROW_SELECTED_HANDLER';
export const ON_SELECT_MADOR_HANDLER = 'ON_SELECT_MADOR_HANDLER';
export const ON_DELETE_MADOR_HANDLER = 'ON_DELETE_MADOR_HANDLER';


